[build]
  base = "apps/player"
  command = "cd ../.. && pnpm install && pnpm exec turbo build --filter=@signage/player"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://5te33orwoc.execute-api.us-east-1.amazonaws.com/development/api/v1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
